### ISSUE TITLE
Seq integration

### ISSUE THREAD

**Issue by Martz94** [Invenietis/ck-core#23]
I was wondering whether integrating the ActivityMonitor stuff you're mentioning in issue #21 with Seq
https://getseq.net/
http://docs.getseq.net/docs
https://github.com/datalust
would make sense/be relevant/useful. 

What do you think?

I don't have time to start working on this right away but let me know if there's interest and I'll see what I can do :-)

Cheers

**Comment by olivier-spinelli** [comment]
I'd love that.
I was planning to support Serilog messages/templates (with a Tag to identify them), but a simple Handler that would be able to send log entries (as they are) to seq would be great!

**Comment by Martz94** [comment]
After some investigation, I don't think it's worth doing at this time.

[Seq API](http://docs.getseq.net/docs/posting-raw-events) is currently rather slim, though sufficient for regular logging frameworks I suppose. 
But if I understand correctly, CK.ActivityMonitor's main selling point is its capacity to offer activity/topic-based logging to structure long/complex "stories". And as of currently Seq wouldn't allow us to take advantage of that feature.

[/related](https://github.com/WildGums/Orc.LogViewer), of interest maybe.

Closing for now.
